#!/usr/bin/env bun
/**
 * Mirrors a fixed subset of the web message catalogs into the macOS app's
 * String Catalog.
 *
 *   bun native/scripts/gen-strings.ts            # writes Localizable.xcstrings
 *   bun native/scripts/gen-strings.ts --check    # fails if the file is stale
 *
 * Paraglide uses {name} placeholders; .xcstrings uses positional %1$@. Names are
 * numbered by first appearance in the EN string and the SAME numbering is applied
 * to DE, so a translator may reorder placeholders freely.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const ROOT = join(import.meta.dir, "..", "..");
const EN = join(ROOT, "ui", "messages", "en.json");
const DE = join(ROOT, "ui", "messages", "de.json");
const OUT = join(ROOT, "native", "Sources", "ShepherdAppCore", "Resources");

/**
 * Every catalog key the macOS app is allowed to use, split by the parallel
 * stream that owns it. A stream edits ONLY its own array, so two branches
 * appending keys produce insertion conflicts a rebase resolves rather than a
 * fight over one list. Keep each array alphabetical.
 *
 * Core: the shell — window, welcome, login, first run, session list, detail
 * header, shared status and effort labels.
 */
export const KEYS_CORE: readonly string[] = [
  "agent_provider_claude",
  "agent_provider_codex",
  "common_cancel",
  "common_close",
  "common_loading",
  "common_retry",
  "common_save",
  "effort_default",
  "effort_label_high",
  "effort_label_low",
  "effort_label_max",
  "effort_label_medium",
  "effort_label_ultra",
  "effort_label_xhigh",
  "login_busy",
  "login_error",
  "login_password_label",
  "login_password_placeholder",
  "login_submit",
  "login_subtitle",
  "native_archive_confirm_action",
  "native_archive_confirm_body",
  "native_archive_confirm_title",
  "native_archive_failed",
  "native_banner_client_too_old",
  "native_banner_mismatch",
  "native_banner_needs_login",
  "native_banner_offline",
  "native_banner_unhealthy",
  "native_detail_no_selection",
  "native_detail_placeholder_body",
  "native_detail_placeholder_title",
  "native_detail_status_label",
  "native_error_first_run",
  "native_error_forbidden",
  "native_error_keychain",
  "native_error_mismatch",
  "native_error_not_found",
  "native_error_offline",
  "native_ios_connecting",
  "native_ios_first_run",
  "native_ios_remove_body",
  "native_ios_welcome_subtitle",
  "native_firstrun_body",
  "native_firstrun_choose",
  "native_firstrun_confirm",
  "native_firstrun_failed",
  "native_firstrun_title",
  "native_install_all_users",
  "native_install_body",
  "native_install_current_user",
  "native_install_existing_body",
  "native_install_existing_title",
  "native_install_failed_body",
  "native_install_failed_title",
  "native_install_later",
  "native_install_open_existing",
  "native_install_title",
  "native_interrupt_failed",
  "native_login_sheet_title",
  "native_menu_session",
  "native_newsession_held",
  "native_newsession_provider_label",
  "native_settings_placeholder_body",
  "native_settings_placeholder_title",
  "native_sidebar_empty",
  "native_sidebar_title",
  "native_signout_failed",
  "native_toolbar_add_server",
  "native_toolbar_archive",
  "native_toolbar_interrupt",
  "native_toolbar_new_session",
  "native_toolbar_servers",
  "native_toolbar_sign_out",
  "native_updates_automatic_check",
  "native_updates_automatic_install",
  "native_updates_check",
  "native_updates_install_note",
  "native_updates_title",
  "native_updates_unavailable",
  "native_url_error_empty",
  "native_url_error_insecure",
  "native_url_error_malformed",
  "native_welcome_connect",
  "native_welcome_local_body",
  "native_welcome_local_detecting",
  "native_welcome_local_found",
  "native_welcome_local_missing",
  "native_welcome_local_recheck",
  "native_welcome_local_title",
  "native_welcome_remote_body",
  "native_welcome_remote_name_label",
  "native_welcome_remote_name_placeholder",
  "native_welcome_remote_title",
  "native_welcome_remote_url_label",
  "native_welcome_remote_url_placeholder",
  "native_welcome_saved_connect",
  "native_welcome_saved_remove",
  "native_welcome_saved_remove_confirm_action",
  "native_welcome_saved_remove_confirm_body",
  "native_welcome_saved_remove_confirm_title",
  "native_welcome_saved_title",
  "native_welcome_subtitle",
  "native_welcome_title",
  "newtask_branch_label",
  "newtask_branch_placeholder",
  "newtask_create_failed",
  "newtask_effort_label",
  "newtask_model_default",
  "newtask_model_label",
  "newtask_prompt_label",
  "newtask_prompt_placeholder",
  "newtask_repo_label",
  "newtask_spawning",
  "newtask_submit",
  "newtask_title",
  "status_archived",
  "status_blocked",
  "status_done",
  "status_idle",
  "status_working",
];

/** Terminal stream (S1). Keep alphabetical. */
export const KEYS_TERMINAL: readonly string[] = [
  "native_terminal_connecting",
  "native_terminal_ended_body",
  "native_terminal_ended_title",
  "native_terminal_prompt_failed",
  "native_terminal_prompt_placeholder",
  "native_terminal_prompt_send",
  "native_terminal_superseded_action",
  "native_terminal_superseded_body",
  "native_terminal_superseded_title",
  "native_terminal_tab_title",
  "native_terminal_unreachable_body",
  "native_terminal_unreachable_title",
];

/**
 * S2 — detail tabs: activity, diff, files, PR status and PR actions. Only this
 * stream edits this array. Keep alphabetical. Everything without the
 * `native_detail_` prefix is an existing web key reused verbatim, which is what
 * the i18n rule prefers.
 */
export const KEYS_DETAIL: readonly string[] = [
  "activity_empty",
  "diff_empty",
  "diff_note_binary",
  "diff_note_no_changes",
  "diff_note_truncated",
  "diff_refresh",
  "diff_stale",
  "files_created_unknown",
  "files_empty",
  "files_link_outside_title",
  "files_load_error",
  "files_source_scratchpad",
  "files_source_worktree",
  "files_worktree_empty",
  "files_worktree_load_error",
  "gitrail_ci_failing",
  "gitrail_ci_none",
  "gitrail_ci_passing",
  "gitrail_ci_pending",
  "gitrail_create_pr",
  "gitrail_merge",
  "gitrail_status_failed",
  "native_detail_action_failed",
  "native_detail_annotation_agent",
  "native_detail_close_confirm_action",
  "native_detail_close_confirm_body",
  "native_detail_close_confirm_title",
  "native_detail_git_none",
  "native_detail_merge_confirm_action",
  "native_detail_merge_confirm_body",
  "native_detail_merge_confirm_title",
  "native_detail_refresh",
  "native_detail_reviewer_label",
  "native_detail_tab_activity",
  "native_detail_tab_diff",
  "native_detail_tab_files",
  "native_detail_tab_git",
  "prbadge_mark_draft",
  "prbadge_mark_ready",
  "prreview_load_failed",
  "prreview_loading",
  "prreview_no_candidates",
  "prreview_title",
  "viewport_diff_annotation_review",
];

/** Keys the Herd sidebar and header strip use. Owned by stream S3 — keep alphabetical. */
export const KEYS_SIDEBAR: readonly string[] = [
  "herd_all_title",
  "herd_awaiting_merge_group",
  "herd_changes_requested_group",
  "herd_ci_failed_group",
  "herd_ci_running_group",
  // `herd_done_empty` is the web's Done-PANEL line. The Done lens is panel-only in the web
  // and ships disabled here (`HerdLens.isAvailable`), so nothing in this build can render it.
  "herd_done_title",
  "herd_draft_awaiting_signoff_group",
  "herd_lenses_label",
  "herd_merge_blocked_group",
  "herd_merged_group",
  "herd_merging_group",
  "herd_next_title",
  "herd_owed_title",
  "herd_ready_empty",
  "herd_ready_group",
  "herd_ready_title",
  "herd_repo_filter_empty",
  "herd_reviewer_running_group",
  "herd_rework_running_group",
  "herd_seg_all",
  "herd_seg_done",
  "herd_seg_next",
  "herd_seg_owed",
  "herd_seg_ready",
  "herd_stage_name_active",
  "herd_waiting_merger_group",
  "herd_waiting_merger_group_multi",
  "herd_waiting_reviewer_group",
  "herd_waiting_reviewer_group_multi",
  "native_herd_counter_active",
  "native_herd_counter_blocked",
  "native_herd_counter_idle",
  "native_herd_counter_total",
  "repo_filter_active_aria",
  "repo_filter_apply_aria",
  "repo_switcher_label",
  "research_badge_label",
  "session_autopilot_paused_label",
  "terminal_badge_label",
  "unitrow_manual_steps",
  "unitrow_quota_error",
  "unitrow_quota_review",
  "unitrow_quota_rework",
  "usage_limits_no_data",
  "usage_limits_window_5h",
  "usage_limits_window_week",
  "usage_subscription_only",
];

/** S4 — the quick-action bar and the "Handlungsbedarf" recap line. Keep alphabetical. */
export const KEYS_ACTIONS: readonly string[] = [
  "amend_failed",
  "amend_original_task",
  "amend_placeholder",
  "amend_recorded",
  "amend_recorded_and_steered",
  "amend_recorded_not_steered",
  "amend_sending",
  "amend_steer_label",
  "amend_steer_offline",
  "amend_submit",
  "amend_title",
  "cardmenu_amend",
  "cardmenu_relaunch",
  "cardmenu_rename",
  "cardmenu_resume",
  "cardmenu_resume_failed",
  "cardmenu_stop",
  "cardmenu_stop_failed",
  "cardmenu_stop_title",
  "cardmenu_stop_toast",
  "feat_visual_recap_title",
  "gitrail_ready",
  "gitrail_ready_aria",
  "gitrail_ready_off_title",
  "gitrail_ready_on_title",
  "native_actions_bar_label",
  "native_actions_failed",
  "native_actions_open_items",
  "native_actions_ready_off",
  "native_actions_ready_on",
  "native_actions_recap_requested",
  "native_actions_relaunch_confirm_action",
  "native_actions_relaunch_confirm_body",
  "native_actions_relaunch_confirm_title",
  "native_actions_resumed",
  "recap_open_items",
  "recap_regenerate",
  "recap_regenerate_failed",
  "recap_verdict_needs_attention",
  "recap_verdict_parked",
  "recap_verdict_ready",
  "relaunch_archive_failed",
  "relaunch_done",
  "relaunch_in_progress",
  "relaunch_issue_unresolved",
  "toast_renamed",
  "viewport_rename_aria",
  "viewport_rename_branch_kept",
  "viewport_rename_failed",
  "viewport_rename_name_taken",
  "viewport_rename_placeholder",
];

/** S5 — local server detection, install, start/stop/restart and the log tail. */
export const KEYS_LOCALSERVER: readonly string[] = [
  "native_local_connect",
  "native_local_error_bun_missing",
  "native_local_error_crash_loop",
  "native_local_error_download",
  "native_local_error_exited",
  "native_local_error_health_timeout",
  "native_local_error_install_failed",
  "native_local_error_invalid_download",
  "native_local_error_not_checkout",
  "native_local_error_runner_missing",
  "native_local_error_runner_timeout",
  "native_local_error_write",
  "native_local_external_app",
  "native_local_external_database",
  "native_local_external_keep",
  "native_local_external_stop_body",
  "native_local_external_stop_title",
  "native_local_external_summary",
  "native_local_external_title",
  "native_local_install",
  "native_local_log_hide",
  "native_local_log_show",
  "native_local_password_body",
  "native_local_password_copy",
  "native_local_password_title",
  "native_local_path_unknown",
  "native_local_recheck",
  "native_local_restart",
  "native_local_start",
  "native_local_state_external",
  "native_local_state_installing",
  "native_local_state_not_installed",
  "native_local_state_running",
  "native_local_state_starting",
  "native_local_state_stopped",
  "native_local_stop",
];

/** S6 — notification titles and bodies. Keep alphabetical. */
export const KEYS_NOTIFICATIONS: readonly string[] = [
  "hold_blocked_awaiting_input",
  "hold_blocked_generic",
  "hold_blocked_menu",
  "hold_blocked_stall",
  "hold_blocked_yes_no",
  "hold_quota_error",
  "hold_quota_plan",
  "hold_quota_review",
  "hold_quota_rework",
  "native_notify_blocked_title",
  "native_notify_done_body",
  "native_notify_done_title",
  "native_notify_manual_steps_body",
  "native_notify_manual_steps_title",
  "native_notify_merge_error_body",
  "native_notify_merge_error_title",
  "native_notify_ready_body",
  "native_notify_ready_title",
  "native_notify_rebase_cap_body",
  "native_notify_rebase_cap_title",
  "native_notify_settings_enabled",
  "native_notify_settings_menu_item",
  "native_notify_settings_permission_ask",
  "native_notify_settings_permission_denied",
  "native_notify_settings_quiet_hint",
  "native_notify_settings_scope",
  "native_notify_settings_title",
  "native_notify_usage_body",
  "native_notify_usage_body_reset",
  "native_notify_usage_title",
  "settings_push_cat_agent",
  "settings_push_cat_ci",
];

/** S7 — the herd classifier: lifecycle group headings the sidebar already has live in
 *  KEYS_SIDEBAR; this array is for the stepper, the row badges and the CI/review banners. */
export const KEYS_HERD: readonly string[] = [
  "herd_waiting_reviewer_group_maintainers",
  "herd_waiting_merger_group_maintainers",
  "activity_active",
  "activity_ci_failure",
  "activity_ci_pending",
  "activity_ci_status",
  "activity_ci_success",
  "activity_closed",
  "activity_merged",
  "activity_progress",
  "activity_review_approved",
  "activity_review_changes",
  "activity_review_reviewing",
  "activity_review_status",
  "activity_stage_implementing",
  "activity_stage_planning",
  "activity_stage_pr",
  "activity_stage_ready",
  "activity_stage_review",
  "activity_starting",
  "clibadge_label_claude",
  "clibadge_label_codex",
  "clibadge_title",
  "criticbadge_changes",
  "criticbadge_commented",
  "criticbadge_error",
  "criticbadge_final",
  "criticbadge_final_title",
  "criticbadge_open_pr",
  "criticbadge_reviewing",
  "criticbadge_reviewing_activity_title",
  "criticbadge_reviewing_title",
  "criticbadge_round",
  "criticbadge_round_title",
  "criticbadge_stalled",
  "criticbadge_stalled_title",
  "criticbadge_title",
  "gitrail_ci_status",
  "gitrail_merge_blocked_behind",
  "gitrail_merge_blocked_checks",
  "gitrail_merge_blocked_conflict",
  "gitrail_merge_blocked_draft",
  "gitrail_merge_blocked_protected",
  "heartbeat_legend_active_desc",
  "heartbeat_legend_active_label",
  "heartbeat_legend_error_desc",
  "heartbeat_legend_error_label",
  "heartbeat_legend_idle_desc",
  "heartbeat_legend_idle_label",
  "heartbeat_pop_intro",
  "issuebadge_label",
  "issuebadge_open_label",
  "issuebadge_title",
  "prbadge_behind",
  "prbadge_behind_title",
  "prbadge_button_title",
  "prbadge_closed",
  "prbadge_conflict",
  "prbadge_conflict_title",
  "prbadge_draft",
  "prbadge_merged",
  "prbadge_open",
  "prbadge_review_approved",
  "prbadge_review_changes",
  "prbadge_review_comment",
  "session_autopilot_complete_label",
  "session_autopilot_complete_title",
  "session_autopilot_paused_title",
  "session_autopilot_unavailable_label",
  "session_autopilot_unavailable_title",
  "status_merging",
  "status_merging_tip",
  "status_ready_tip",
  "status_ready_to_merge",
  "stepper_desc_implementing",
  "stepper_desc_planning",
  "stepper_desc_pr",
  "stepper_desc_ready",
  "stepper_desc_review",
  "stepper_legend_done",
  "stepper_legend_now",
  "stepper_legend_pending",
  "stepper_legend_skipped",
  "stepper_open_hint",
  "unitrow_changes_requested",
  "unitrow_changes_requested_title",
  "unitrow_merge_blocked",
  "unitrow_merge_blocked_title",
  "unitrow_unknown_reviewer",
];

/** S8 — plan gates: the badge chips, the plan panel, the visual-block renderer and the
 *  question form. */
export const KEYS_PLAN: readonly string[] = [
  "hold_cta_answer",
  "hold_cta_answer_title",
  "plangate_changes",
  "plangate_edited",
  "plangate_error",
  "plangate_menu_editor_label",
  "plangate_menu_editor_reset",
  "plangate_menu_editor_send",
  "plangate_menu_label",
  "plangate_menu_open_plan",
  "plangate_menu_rereview",
  "plangate_menu_send_changes",
  "plangate_menu_why",
  "plangate_menu_why_body",
  "plangate_planning",
  "plangate_ready",
  "plangate_repair_no_findings",
  "plangate_repair_send_failed",
  "plangate_repair_sent",
  "plangate_repair_steer",
  "plangate_review_at_cap",
  "plangate_review_skipped_stalled",
  "plangate_review_spends_round",
  "plangate_review_started",
  "plangate_reviewing",
  "plangate_tip_changes",
  "plangate_tip_changes_stalled",
  "plangate_tip_edited",
  "plangate_tip_error",
  "plangate_tip_planning",
  "plangate_tip_ready",
  "plangate_tip_reviewing",
  "plangate_tip_reviewing_env",
  "plangate_tip_view",
  "plangate_title",
  "plangate_view",
  "planpanel_back_aria",
  "planpanel_edited_note",
  "planpanel_empty",
  "planpanel_env_aria",
  "planpanel_env_docs_link",
  "planpanel_env_help_aria",
  "planpanel_env_plan",
  "planpanel_env_popover_body",
  "planpanel_env_popover_title",
  "planpanel_env_review",
  "planpanel_env_unavailable",
  "planpanel_findings",
  "planpanel_go",
  "planpanel_membrane_launch",
  "planpanel_native_go_confirm",
  "planpanel_native_go_failed",
  "planpanel_native_not_releasable",
  "planpanel_no_verdict",
  "planpanel_plan_unavailable",
  "planpanel_proposed_caption",
  "planpanel_quota_dismiss",
  "planpanel_quota_dismissing",
  "planpanel_quota_failed",
  "planpanel_quota_not_stalled",
  "planpanel_quota_resume",
  "planpanel_quota_resuming",
  "planpanel_quota_unreachable",
  "planpanel_review_already_approved",
  "planpanel_review_at_cap",
  "planpanel_review_at_cap_no_resume",
  "planpanel_review_failed",
  "planpanel_review_failed_auth",
  "planpanel_review_failed_spawn",
  "planpanel_review_failed_worktree",
  "planpanel_review_nothing_to_review",
  "planpanel_review_now",
  "planpanel_review_plan_unavailable",
  "planpanel_reviewing",
  "planpanel_reviewing_env",
  "planpanel_status_changes",
  "planpanel_status_changes_stalled",
  "planpanel_status_edited",
  "planpanel_status_error",
  "planpanel_status_planning",
  "planpanel_status_ready",
  "planpanel_status_reviewing",
  "planpanel_status_view",
  "planpanel_title",
  "planpanel_verdict",
  "qform_freeform_placeholder",
  "qform_kind_freeform",
  "qform_kind_multi",
  "qform_kind_multi_optional",
  "qform_kind_single",
  "qform_native_confirm_body",
  "qform_sent",
  "qform_sent_undelivered",
  "qform_submit",
  "qform_submit_error",
  "qform_submitting",
  "vblock_apiendpoint_deprecated",
  "vblock_apiendpoint_params",
  "vblock_apiendpoint_required",
  "vblock_apiendpoint_responses",
  "vblock_callout_decision",
  "vblock_callout_info",
  "vblock_callout_risk",
  "vblock_callout_success",
  "vblock_callout_warning",
  "vblock_code_truncated",
  "vblock_datamodel_fk",
  "vblock_datamodel_nullable",
  "vblock_datamodel_pk",
  "vblock_datamodel_relations",
  "vblock_datamodel_was",
  "vblock_diff_highlighted_heading",
  "vblock_filetree_added",
  "vblock_filetree_modified",
  "vblock_filetree_removed",
  "vblock_filetree_renamed",
  "vblock_inferred",
  "vblock_mermaid_error",
  "vblock_mermaid_expand",
  "vblock_native_not_rendered",
  "vblock_native_wireframe_omitted",
  "vblock_wireframe_mockup_label",
  "vblock_wireframe_surface_browser",
  "vblock_wireframe_surface_desktop",
  "vblock_wireframe_surface_mobile",
  "vblock_wireframe_surface_panel",
  "vblock_wireframe_surface_popover",
];

/** S9 — merge, automation and post-merge steps. */
export const KEYS_MERGE: readonly string[] = [
  "automerge_state_merge_error",
  "automerge_state_merging",
  "automerge_state_rebase_cap",
  "automerge_state_rebasing",
  "automerge_state_stacked",
  "drain_paused_blocked",
  "drain_paused_changes",
  "drain_paused_credits",
  "drain_paused_epic_base",
  "drain_paused_error",
  "drain_paused_generic",
  "drain_paused_usage",
  "buildqueue_start",
  "buildqueue_start_steer",
  "clearmerged_confirm",
  "clearmerged_leftovers",
  "clearmerged_probes_unavailable",
  "clearmerged_title",
  "herd_merge_train_prompt",
  "mergeconfirm_confirm",
  "mergeconfirm_handoff_merger",
  "mergeconfirm_handoff_reviewer",
  "mergeconfirm_review_block",
  "native_merge_ack",
  "native_merge_action_failed",
  "native_merge_add",
  "native_merge_approve",
  "native_merge_automerge",
  "native_merge_autopilot",
  "native_merge_base",
  "native_merge_complete",
  "native_merge_delete_branch",
  "native_merge_excluded",
  "native_merge_inherit",
  "native_merge_load_failed",
  "native_merge_method",
  "native_merge_move_down",
  "native_merge_move_up",
  "native_merge_off",
  "native_merge_on",
  "native_merge_overview",
  "native_merge_paused",
  "native_merge_queue",
  "native_merge_redeploy",
  "native_merge_remove",
  "native_merge_step",
  "native_merge_step_detail",
  "native_merge_train",
  "native_merge_train_warning",
  "owed_dismiss",
  "owed_dismiss_confirm",
  "owed_post_merge_badge",
  "owed_tracking_issue",
];

/** S10 — held tasks, up-next, done/recaps, halt and retry. */
export const KEYS_QUEUES: readonly string[] = [
  "broadcast_clear_all",
  "broadcast_confirm_send",
  "broadcast_failed",
  "broadcast_no_sessions",
  "broadcast_placeholder",
  "broadcast_select_all",
  "broadcast_send_to",
  "broadcast_sending",
  "broadcast_steer",
  "broadcast_targets",
  "broadcast_textarea_aria",
  "broadcast_title",
  "common_issues_load_failed",
  "done_recap_finished",
  "done_recap_panel_aria",
  "donerecap_bringback",
  "donerecap_bringback_confirm",
  "halt_all_aria",
  "halt_arm",
  "halt_arm_aria",
  "halt_confirm",
  "halt_done",
  "halt_failed",
  "halt_menu_item",
  "herd_done_empty",
  "newtask_edit_held_failed",
  "newtask_edit_held_saving",
  "newtask_edit_held_submit",
  "newtask_edit_held_title",
  "owed_empty",
  "owed_repo_filter_empty",
  "owed_title",
  "recap_changed_files",
  "recap_empty_legacy",
  "recap_failed",
  "recap_failure_auth_action",
  "recap_failure_auth_headline",
  "recap_failure_default_model",
  "recap_failure_detail",
  "recap_failure_details",
  "recap_failure_invalid_result_headline",
  "recap_failure_launch_headline",
  "recap_failure_model",
  "recap_failure_no_result_headline",
  "recap_failure_provider",
  "recap_failure_provider_action",
  "recap_failure_source_action",
  "recap_failure_source_headline",
  "recap_failure_timeout_headline",
  "recap_generating",
  "recap_predates_feature",
  "recap_unavailable",
  "restore_branch_gone",
  "restore_branch_in_use",
  "restore_cannot",
  "restore_done",
  "restore_failed",
  "restore_in_progress",
  "restore_not_archived",
  "retry_arm",
  "retry_confirm",
  "retry_continue_steer",
  "retry_empty",
  "retry_failed",
  "retry_halted_badge",
  "retry_title",
  "toast_auto_revived",
  "toast_broadcast_delivered",
  "toast_broadcast_result",
  "toast_broadcast_skipped_terminals",
  "toast_held_edit_saved",
  "toast_retry_done",
  "toast_revive_all",
  "toast_revive_all_failed",
  "toast_revive_all_result",
  "toast_sessions_stranded",
  "topbar_held_badge",
  "topbar_held_discard",
  "native_held_discard_confirm",
  "topbar_held_discard_failed",
  "topbar_held_discarding",
  "topbar_held_edit",
  "topbar_held_empty",
  "topbar_held_original_cli",
  "native_held_reason_usage",
  "native_held_reason_capacity",
  "native_held_reason_unknown",
  "topbar_held_spawn_cli_label",
  "topbar_held_spawn_failed",
  "topbar_held_spawn_now",
  "topbar_held_spawning",
  "topbar_held_title",
  "upnext_batch_aria",
  "upnext_clear_selection",
  "upnext_confirm",
  "upnext_confirm_yes",
  "upnext_empty",
  "upnext_held",
  "upnext_normal_section",
  "upnext_picker_confirm",
  "upnext_picker_title",
  "upnext_pill_epic",
  "upnext_pill_priority",
  "upnext_priority_section",
  "upnext_refresh",
  "upnext_repo_filter_empty",
  "upnext_select_aria",
  "upnext_show_all",
  "upnext_show_less",
  "upnext_sort_aria",
  "upnext_sort_by",
  "upnext_sort_newest",
  "upnext_sort_oldest",
  "upnext_sort_recommended",
  "upnext_sort_title_asc",
  "upnext_sort_title_desc",
  "upnext_start",
  "upnext_start_failed",
  "upnext_start_selected",
  "upnext_started",
  "upnext_title",
  "upnext_updated_ago",
  "usage_prompt_tokens_unit",
];

/** S11 — the composer: create fields, slash commands, steers, attachments. */
export const KEYS_COMPOSE: readonly string[] = [
  "recommend_copy",
  "recommend_copied",
  "issuespanel_filter_placeholder",
  "issuespanel_no_match",
  "leftover_desc",
  "leftover_terminate",
  "recommend_inject",
  "cardmenu_decommission",
  "cardmenu_replace_with",
  "cardmenu_start_variant",
  "experiment_continue_handoff_label",
  "experiment_continue_mode_resume",
  "experiment_continue_mode_summarize",
  "experiment_continue_scope",
  "experiment_replace_confirm",
  "experiment_replace_title",
  "experiment_variant_confirm",
  "experiment_variant_title",
  "leftover_close_only",
  "leftover_port",
  "leftover_title",
  "native_compose_leftovers_kept",
  "native_compose_probes_unavailable",
  "native_compose_share_prompt",
  "native_compose_steer_down",
  "native_compose_steer_up",
  "recommend_err_no_history",
  "recommend_err_spawn_failed",
  "recommend_err_timeout",
  "recommend_err_unavailable",
  "recommend_loading",
  "recommend_result_hint",
  "recommend_title",
  "steerbar_edit",
  "steerseditor_add",
  "steerseditor_empty",
  "steerseditor_field_emoji",
  "steerseditor_label_aria",
  "steerseditor_placement_bar",
  "steerseditor_placement_issues",
  "steerseditor_remove",
  "steerseditor_repos_all",
  "steerseditor_scope_all_short",
  "steerseditor_scope_none_error",
  "steerseditor_text_aria",
  "steerseditor_title",
  "native_compose_dictation_deferred",
  "newtask_readiness_ready",
  "newtask_readiness_branches",
  "newtask_readiness_empty_prompt",
  "newtask_readiness_no_repo",
  "newtask_readiness_repairing",
  "keymap_mod_ctrl",
  "keymap_mod_alt",
  "keymap_mod_shift",
  "keymap_hold_verb",
  "keymap_zone_global",
  "keymap_zone_prompt",
  "keymap_zone_context",
  "keymap_zone_options",
  "keymap_submit",
  "keymap_close",
  "keymap_hold",
  "keymap_sheet",
  "keymap_focus_prompt",
  "keymap_issue_token",
  "keymap_command_token",
  "keymap_paste_image",
  "keymap_attach",
  "keymap_dictate",
  "keymap_repo",
  "keymap_branch",
  "keymap_repo_prev",
  "keymap_repo_next",
  "keymap_issue_filter",
  "keymap_sources_tab",
  "keymap_list_nav",
  "keymap_list_pick",
  "keymap_mode_code",
  "keymap_mode_research",
  "keymap_mode_epic",
  "keymap_mode_plain",
  "keymap_engine",
  "keymap_model",
  "keymap_plan_gate",
  "keymap_autopilot",
  "keymap_sheet_title",
  "keymap_sheet_context",
  "keymap_sheet_dismiss",
  "keymap_sheet_aria",
  "keymap_footer_idle",
  "keymap_footer_held",
  "keymap_mode_research_short",
  "newtask_spawn_phase_base",
  "newtask_spawn_phase_worktree",
  "newtask_spawn_phase_prompt",
  "newtask_spawn_phase_launch",
  "newtask_spawn_phase_agent",
  "newtask_spawn_why_base",
  "newtask_spawn_why_worktree",
  "newtask_spawn_why_prompt",
  "newtask_spawn_why_launch",
  "newtask_spawn_why_agent",
  "newtask_spawn_slow",
  "newtask_spawn_cancel",
  "newtask_spawn_canceling",
  "newtask_spawn_canceled",
  "newtask_spawn_seconds",
  "newtask_spawn_progress_aria",
  "newtask_submit_in_repo",
  "newtask_hold_for_reset",
  "newtask_submit_anyway",

  "newtask_shape_label",
  "newtask_shape_aria",
  "newtask_shape_hint",
  "shape_heading",
  "shape_running",
  "shape_questions_count",
  "shape_s_problem",
  "shape_s_outcome",
  "shape_s_constraints",
  "shape_s_nongoals",
  "shape_use_brief",
  "shape_discard",
  "shape_err_timeout",
  "shape_err_spawn_failed",
  "shape_err_unavailable",
  "shape_err_empty_prompt",
  "shape_err_compose",
  "model_configured_fable_latest",
  "model_configured_opus_1m_latest",
  "model_configured_opus_latest",
  "model_cost_high",
  "model_cost_low",
  "model_cost_premium",
  "model_cost_standard",
  "model_guidance_auto",
  "model_guidance_claude_fable",
  "model_guidance_claude_fable_5_1",
  "model_guidance_claude_haiku",
  "model_guidance_claude_opus",
  "model_guidance_claude_opus_1m",
  "model_guidance_claude_opus_5",
  "model_guidance_claude_opus_5_1m",
  "model_guidance_claude_sonnet",
  "model_guidance_claude_sonnet_1m",
  "model_guidance_codex_5",
  "model_guidance_codex_51",
  "model_guidance_codex_51_codex",
  "model_guidance_codex_53",
  "model_guidance_codex_54",
  "model_guidance_codex_55",
  "model_guidance_codex_56_luna",
  "model_guidance_codex_56_sol",
  "model_guidance_codex_56_terra",
  "model_guidance_codex_5_codex",
  "model_guidance_codex_6_astra",
  "model_guidance_codex_o3",
  "model_guidance_default",
  "model_guidance_inherit",
  "model_guidance_unknown",
  "model_label_fable_5_1",
  "model_label_opus_5",
  "model_label_opus_5_1m",
  "model_label_sonnet_1m",
  "model_tag_balanced",
  "model_tag_budget",
  "model_tag_long_context",
  "model_tag_max",
  "model_tag_provider_default",
  "model_tag_strong",

  "files_upload_too_large",
  "newtask_agent_provider_label",
  "newtask_agent_provider_codex_alpha_badge",
  "newtask_provider_capacity_title",
  "newtask_provider_capacity_meter_window_aria",
  "newtask_provider_capacity_free",
  "newtask_provider_capacity_free_until",
  "newtask_provider_capacity_unavailable",
  "newtask_capacity_all",
  "newtask_capacity_all_aria",
  "newtask_attach_image",
  "newtask_remove_image_aria",
  "newtask_uploading",
  "newtask_upload_failed",
  "newtask_upload_percent",
  "newtask_upload_unknown_reason",
  "newtask_agent_provider_codex_alpha_note",
  "newtask_agent_provider_codex_note",
  "newtask_agent_provider_codex_suggested_for_hold",
  "newtask_alpha_caution",
  "newtask_alpha_details",
  "newtask_autopilot_hint",
  "newtask_group_guards",
  "newtask_guard_autopilot",
  "newtask_guard_plan_gate",
  "newtask_plan_gate_hint",
  "newtask_research_sandbox_note",
  "newtask_sandbox_default",
  "newtask_sandbox_hint",
  "newtask_sandbox_label",
  "newtask_toggle_off",
  "newtask_toggle_on",
  "sandbox_profile_autonomous",
  "sandbox_profile_standard",
  "sandbox_profile_trusted",
  "newtask_group_mode",
  "newtask_guards_none_epic",
  "newtask_guards_none_plain",
  "newtask_guards_none_research",
  "newtask_mode_code",
  "newtask_mode_epic",
  "newtask_mode_plain",
  "newtask_mode_research",
  "newtask_base_missing",
  "newtask_chip_from",
  "newtask_init_commit",
  "newtask_init_commit_failed",
  "newtask_init_commit_running",
  "newtask_readiness_base_missing",
  "newtask_upstream_checking",
  "newtask_upstream_behind",
  "newtask_upstream_diverged",
  "common_issues_lightweight",
  "common_no_open_issues",
  "issue_filter_button",
  "issue_filter_button_aria",
  "issue_filter_heading",
  "issues_filter_active_label",
  "issues_filter_active_title",
  "issues_filter_all_assigned_to_others",
  "issues_filter_all_blocked",
  "issues_filter_all_in_progress",
  "issues_filter_all_sub_issues",
  "issues_filter_author_all",
  "issues_filter_author_heading",
  "issues_filter_blocked_label",
  "issues_filter_blocked_title",
  "issues_filter_labels_heading",
  "issues_filter_mine_label",
  "issues_filter_mine_title",
  "issues_filter_no_match",
  "issues_filter_subissues_label",
  "issues_filter_subissues_title",
  "newtask_issue_prompt_template",
  "newtask_issue_remove_aria",
  "newtask_provider_constraint_body",
  "newtask_provider_constraint_title",
  "promptsources_collapse_row",
  "promptsources_commands_filter",
  "promptsources_commands_tab",
  "promptsources_issues_tab",
  "promptsources_more_row",
  "promptsources_no_commands",
  "promptsources_no_github",
  "promptsources_open_count",
  "promptsources_title",
];

/** S12 — the settings panes, the command menu and the usage gauges. */
export const KEYS_SETTINGS: readonly string[] = [
  "native_recovery_reopen",
  "native_terminal_session_unavailable",
  "native_terminal_session_not_resumable",
  "native_terminal_recovery_failed",
  "native_settings_diagnostics_failed_title",
  "native_settings_diagnostics_failed_body",
  "native_settings_diagnostics_loading",
  "native_recovery_runner_body",
  "native_recovery_runner_title",
  "native_recovery_server_body",
  "native_recovery_server_title",
  "native_recovery_start_runner",
  "native_recovery_unknown_body",
  "native_recovery_unknown_title",

  "native_settings_search",
  "settings_auth_mode_subscription",
  "settings_auth_mode_apikey",
  "settings_auth_mode_hint",
  "settings_access_created",
  "settings_access_last_used",
  "settings_access_never_used",
  "settings_access_expires",
  "settings_access_expires_never",
  "settings_access_expired",
  "settings_access_scope_unknown",
  "settings_access_scope_read_hint",
  "settings_access_scope_submit_hint",
  "settings_access_scope_full_hint",

  "diagnostics_all_ok",
  "diagnostics_doc_link",
  "diagnostics_fix",
  "diagnostics_fix_action_claude_trust",
  "diagnostics_fix_action_host_capacity",
  "diagnostics_fix_action_tmp_inodes",
  "diagnostics_fix_confirm_body",
  "diagnostics_fix_confirm_run",
  "diagnostics_fix_confirm_run_code",
  "diagnostics_fix_confirm_run_host_capacity",
  "diagnostics_fix_confirm_run_tmp_inodes",
  "diagnostics_fix_confirm_title",
  "diagnostics_fix_confirm_title_code",
  "diagnostics_fix_confirm_title_host_capacity",
  "diagnostics_fix_confirm_title_tmp_inodes",
  "diagnostics_fix_failed",
  "diagnostics_fix_running",
  "diagnostics_fix_success",
  "diagnostics_fix_unresolved",
  "diagnostics_fix_unresolved_code",
  "diagnostics_fix_unresolved_host_capacity",
  "diagnostics_fix_unresolved_tmp_inodes",
  "diagnostics_herdr_downgrade",
  "diagnostics_herdr_repair",
  "diagnostics_hint_bun_missing",
  "diagnostics_hint_bun_ok",
  "diagnostics_hint_bun_outdated",
  "diagnostics_hint_claude_install_diverged",
  "diagnostics_hint_claude_install_native_on_path",
  "diagnostics_hint_claude_install_native_residue",
  "diagnostics_hint_claude_install_ok",
  "diagnostics_hint_claude_missing",
  "diagnostics_hint_claude_ok",
  "diagnostics_hint_claude_optional",
  "diagnostics_hint_claude_trust_ok",
  "diagnostics_hint_claude_trust_untrusted",
  "diagnostics_hint_codex_missing",
  "diagnostics_hint_codex_model_chatgpt_incompatible",
  "diagnostics_hint_codex_ok",
  "diagnostics_hint_codex_optional",
  "diagnostics_hint_gh_missing",
  "diagnostics_hint_gh_not_authenticated",
  "diagnostics_hint_gh_not_required",
  "diagnostics_hint_gh_ok",
  "diagnostics_hint_gh_unverified",
  "diagnostics_hint_git_missing",
  "diagnostics_hint_git_ok",
  "diagnostics_hint_gitcap_ok",
  "diagnostics_hint_gitcap_old",
  "diagnostics_hint_herdr_health_leftover",
  "diagnostics_hint_herdr_health_ok",
  "diagnostics_hint_herdr_health_uninspectable",
  "diagnostics_hint_herdr_missing",
  "diagnostics_hint_herdr_offline",
  "diagnostics_hint_herdr_ok",
  "diagnostics_hint_herdr_outdated",
  "diagnostics_hint_herdr_restart",
  "diagnostics_hint_herdr_unknown",
  "diagnostics_hint_herdr_unsupported",
  "diagnostics_hint_host_capacity_herdr_unbounded",
  "diagnostics_hint_host_capacity_ok",
  "diagnostics_hint_host_capacity_pressure",
  "diagnostics_hint_host_capacity_unbounded",
  "diagnostics_hint_host_capacity_uninspectable",
  "diagnostics_hint_node_missing",
  "diagnostics_hint_node_ok",
  "diagnostics_hint_node_outdated",
  "diagnostics_hint_preview_probes_idle",
  "diagnostics_hint_preview_probes_ok",
  "diagnostics_hint_preview_probes_stale",
  "diagnostics_hint_preview_probes_unavailable",
  "diagnostics_hint_preview_probes_uninspectable",
  "diagnostics_hint_preview_probes_unsupported",
  "diagnostics_hint_pwa_android",
  "diagnostics_hint_pwa_ios",
  "diagnostics_hint_pwa_optional",
  "diagnostics_hint_sandbox_membrane_broken",
  "diagnostics_hint_sandbox_membrane_ok",
  "diagnostics_hint_sandbox_membrane_uninspectable",
  "diagnostics_hint_tailscale_missing",
  "diagnostics_hint_tailscale_not_serving",
  "diagnostics_hint_tailscale_ok",
  "diagnostics_hint_tailscale_serve_denied",
  "diagnostics_hint_tmp_entries_critical",
  "diagnostics_hint_tmp_entries_high",
  "diagnostics_hint_tmp_entries_ok",
  "diagnostics_hint_tmp_inodes_critical",
  "diagnostics_hint_tmp_inodes_high",
  "diagnostics_hint_tmp_inodes_ok",
  "diagnostics_hint_tmp_inodes_uninspectable",
  "diagnostics_label_bun",
  "diagnostics_label_claude",
  "diagnostics_label_claude_install",
  "diagnostics_label_claude_trust",
  "diagnostics_label_codex",
  "diagnostics_label_gh",
  "diagnostics_label_git",
  "diagnostics_label_git_mergetree",
  "diagnostics_label_herdr",
  "diagnostics_label_herdr_health",
  "diagnostics_label_host_capacity",
  "diagnostics_label_node",
  "diagnostics_label_preview_probes",
  "diagnostics_label_pwa_install",
  "diagnostics_label_sandbox_membrane",
  "diagnostics_label_tailscale",
  "diagnostics_label_tmp_inodes",
  "diagnostics_learn_more",
  "diagnostics_load_error",
  "diagnostics_pip_label",
  "diagnostics_rerun",
  "diagnostics_rerun_error",
  "diagnostics_state_error",
  "diagnostics_state_installed",
  "diagnostics_state_not_installed",
  "diagnostics_state_ok",
  "diagnostics_state_optional",
  "diagnostics_state_warning",
  "diagnostics_subtitle",
  "diagnostics_title",
  "native_settings_access",
  "native_settings_action_failed",
  "native_settings_active_token_protected",
  "native_settings_api_key",
  "native_settings_automation_notice",
  "native_settings_browse_root",
  "native_settings_clis",
  "native_settings_colorblind",
  "native_settings_command_palette",
  "native_settings_command_search",
  "native_settings_choose_profile",
  "native_settings_connect",
  "native_settings_contrast",
  "native_settings_credits",
  "native_settings_dark",
  "native_settings_days",
  "native_settings_diagnose",
  "native_settings_diagnostic_unknown",
  "native_settings_env_token",
  "native_settings_field_authmode",
  "native_settings_field_autopilotcli",
  "native_settings_field_autopiloteffort",
  "native_settings_field_autopilotmodel",
  "native_settings_field_autoreviveenabled",
  "native_settings_field_blockjudgemode",
  "native_settings_field_criticcli",
  "native_settings_field_criticeffort",
  "native_settings_field_criticmodel",
  "native_settings_field_defaultagentprovider",
  "native_settings_field_defaultcodexmodel",
  "native_settings_field_defaulteffort",
  "native_settings_field_defaultmodel",
  "native_settings_field_distillercli",
  "native_settings_field_distillereffort",
  "native_settings_field_distillerintervaldays",
  "native_settings_field_distillermodel",
  "native_settings_field_docagentcli",
  "native_settings_field_docagenteffort",
  "native_settings_field_docagentmodel",
  "native_settings_field_extracreditsdrainceiling",
  "native_settings_field_fableavailable",
  "native_settings_field_houserulerelevance",
  "native_settings_field_judgedailyusd",
  "native_settings_field_judgeenabled",
  "native_settings_field_mergesuggestcli",
  "native_settings_field_mergesuggesteffort",
  "native_settings_field_mergesuggestmodel",
  "native_settings_field_namercli",
  "native_settings_field_namereffort",
  "native_settings_field_namermodel",
  "native_settings_field_operatorlanguage",
  "native_settings_field_optimizercli",
  "native_settings_field_optimizereffort",
  "native_settings_field_optimizermodel",
  "native_settings_field_plannercli",
  "native_settings_field_plannereffort",
  "native_settings_field_plannermodel",
  "native_settings_field_planreviewcyclescap",
  "native_settings_field_prreviewcyclescap",
  "native_settings_field_recapcli",
  "native_settings_field_recapeffort",
  "native_settings_field_recapmodel",
  "native_settings_field_reducedpushmode",
  "native_settings_field_remotecontrolatstartup",
  "native_settings_field_sessionhousekeepingenabled",
  "native_settings_field_telemetryconsent",
  "native_settings_field_tuidisablemouse",
  "native_settings_field_tuifullscreen",
  "native_settings_field_upnextskipclipicker",
  "native_settings_field_usagedowngradeenabled",
  "native_settings_field_usagedowngrademodel",
  "native_settings_field_usagedowngradepct",
  "native_settings_field_usageholdautorelease",
  "native_settings_field_usageholdenabled",
  "native_settings_field_usageholdpct",
  "native_settings_fix",
  "native_settings_fix_confirm",
  "native_settings_fork",
  "native_settings_fork_target",
  "native_settings_full_motion",
  "native_settings_general",
  "native_settings_key_absent",
  "native_settings_key_confirm",
  "native_settings_key_present",
  "native_settings_key_save",
  "native_settings_light",
  "native_settings_load_failed",
  "native_settings_lock_access",
  "native_settings_login_failed",
  "native_settings_merger",
  "native_settings_model_usage",
  "native_settings_motion",
  "native_settings_never",
  "native_settings_no_commands",
  "native_settings_notifications",
  "native_settings_observed_absent",
  "native_settings_observed_session",
  "native_settings_observed_week",
  "native_settings_open",
  "native_settings_parent",
  "native_settings_people_unavailable",
  "native_settings_plan_bounds",
  "native_settings_pr_bounds",
  "native_settings_pull",
  "native_settings_reduced_motion",
  "native_settings_reduced_push",
  "native_settings_refresh_diagnostics",
  "native_settings_repo",
  "native_settings_repo_autoaddressenabled",
  "native_settings_repo_autodrainenabled",
  "native_settings_repo_autolabel",
  "native_settings_repo_automergeenabled",
  "native_settings_repo_autooptimizeflagged",
  "native_settings_repo_autopilotenabled",
  "native_settings_repo_buildqueueenabled",
  "native_settings_repo_confirm",
  "native_settings_repo_criticallprs",
  "native_settings_repo_criticenabled",
  "native_settings_repo_criticsmelllensenabled",
  "native_settings_repo_defaulteffort",
  "native_settings_repo_defaultmodel",
  "native_settings_repo_draftmode",
  "native_settings_repo_egressextrahosts",
  "native_settings_repo_epicstacksenabled",
  "native_settings_repo_hidden",
  "native_settings_repo_learningsenabled",
  "native_settings_repo_manualstepsissueenabled",
  "native_settings_repo_maxauto",
  "native_settings_repo_plangateenabled",
  "native_settings_repo_previewopenmode",
  "native_settings_repo_previewstartcommand",
  "native_settings_repo_previewstartscript",
  "native_settings_repo_prewarmepiclandingci",
  "native_settings_repo_repomode",
  "native_settings_repo_sandboxprofile",
  "native_settings_repo_signoffauthority",
  "native_settings_repo_usageceilingpct",
  "native_settings_retention",
  "native_settings_reviewer",
  "native_settings_revoke",
  "native_settings_revoke_confirm",
  "native_settings_roles_push_notice",
  "native_settings_roles_save",
  "native_settings_scope_full",
  "native_settings_scope_read",
  "native_settings_scope_submit",
  "native_settings_select_repo",
  "native_settings_stale",
  "native_settings_subscription_only",
  "native_settings_sync",
  "native_settings_system",
  "native_settings_theme",
  "native_settings_token_create",
  "native_settings_token_expiry",
  "native_settings_token_failed",
  "native_settings_token_login",
  "native_settings_token_name",
  "native_settings_token_once",
  "native_settings_token_scope",
  "native_settings_usage",
  "native_settings_usage_all",
  "native_settings_use_folder",
  "native_settings_verify_confirm",
  "native_settings_verify_failed",
  "native_settings_verify_key",
  "native_settings_verify_ok",
  "native_settings_workspace",
  "native_settings_no_profile_title",
  "native_settings_no_profile_summary",
  "native_settings_remote_inactive_title",
  "native_settings_remote_inactive_summary",
  "native_settings_local_offline_title",
  "native_settings_local_offline_summary",
  "native_settings_local_active_title",
  "native_settings_local_active_summary",
];

/**
 * The manifest the catalog is generated from. Order here does not reach the
 * output — `build()` sorts before emitting — but is fixed so the concatenation
 * is easy to assert.
 */
export const KEYS: readonly string[] = [
  ...KEYS_CORE,
  ...KEYS_TERMINAL,
  ...KEYS_DETAIL,
  ...KEYS_SIDEBAR,
  ...KEYS_ACTIONS,
  ...KEYS_LOCALSERVER,
  ...KEYS_NOTIFICATIONS,
  ...KEYS_HERD,
  ...KEYS_PLAN,
  ...KEYS_MERGE,
  ...KEYS_QUEUES,
  ...KEYS_COMPOSE,
  ...KEYS_SETTINGS,
];

/**
 * Keys appearing more than once, sorted. Two streams claiming the same key is an
 * authoring mistake the sorted, de-duplicating emit would otherwise hide: the
 * catalog would be right and `KEYS.length` would be a lie.
 */
export function duplicateKeys(keys: readonly string[]): string[] {
  const seen = new Set<string>();
  const dupes = new Set<string>();
  for (const key of keys) {
    if (seen.has(key)) dupes.add(key);
    else seen.add(key);
  }
  return [...dupes].sort();
}

type Catalog = Record<string, string>;

function load(path: string): Catalog {
  const raw = JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;
  const out: Catalog = {};
  for (const [k, v] of Object.entries(raw)) if (typeof v === "string") out[k] = v;
  return out;
}

/**
 * {name} -> %N$@, numbered by first appearance in `order`.
 *
 * `%` is only escaped to `%%` when the string carries at least one placeholder
 * (`order.size > 0`): those strings go through `String(format:)` at runtime
 * (`L.t(key, args...)`), where a bare `%` would be misread as a conversion.
 * A string with no placeholders is read via `L.t(key)`, which returns
 * `String(localized:)` verbatim with no format pass — escaping `%` there
 * would print a literal `%%` in the UI.
 */
export function convert(value: string, order: Map<string, number>): string {
  const escaped = order.size === 0 ? value : value.replace(/%/g, "%%");
  return escaped.replace(/\{(\w+)\}/g, (_m, name: string) => {
    const index = order.get(name);
    if (index === undefined) throw new Error(`unknown placeholder {${name}}`);
    return `%${index}$@`;
  });
}

export function placeholderOrder(en: string): Map<string, number> {
  const order = new Map<string, number>();
  for (const m of en.matchAll(/\{(\w+)\}/g)) {
    const name = m[1]!;
    if (!order.has(name)) order.set(name, order.size + 1);
  }
  return order;
}

export function build() {
  const en = load(EN);
  const de = load(DE);

  const dupes = duplicateKeys(KEYS);
  if (dupes.length > 0) {
    throw new Error(`keys claimed by more than one stream manifest: ${dupes.join(", ")}`);
  }

  const missing: string[] = [];
  for (const key of KEYS) {
    if (en[key] === undefined) missing.push(`en.json: ${key}`);
    if (de[key] === undefined) missing.push(`de.json: ${key}`);
  }
  if (missing.length > 0) {
    throw new Error(`missing catalog keys:\n  ${missing.join("\n  ")}`);
  }

  const strings: Record<
    string,
    {
      comment?: string;
      extractionState: string;
      localizations: Record<"en" | "de", { stringUnit: { state: string; value: string } }>;
    }
  > = {};
  for (const key of [...KEYS].sort()) {
    const order = placeholderOrder(en[key]!);
    const comment =
      order.size === 0 ? undefined : [...order].map(([name, i]) => `%${i}$@ = ${name}`).join(", ");
    strings[key] = {
      ...(comment ? { comment } : {}),
      extractionState: "manual",
      localizations: {
        de: { stringUnit: { state: "translated", value: convert(de[key]!, order) } },
        en: { stringUnit: { state: "translated", value: convert(en[key]!, order) } },
      },
    };
  }

  return { sourceLanguage: "en", strings, version: "1.0" };
}

export function stringsLiteral(value: string): string {
  const escaped = Array.from(value, (character) => {
    switch (character) {
      case "\\":
        return "\\\\";
      case '"':
        return '\\"';
      case "\n":
        return "\\n";
      case "\r":
        return "\\r";
      case "\t":
        return "\\t";
      default: {
        const code = character.charCodeAt(0);
        return code < 0x20 ? "\\U" + code.toString(16).padStart(4, "0") : character;
      }
    }
  }).join("");
  return '"' + escaped + '"';
}

export function renderStrings(entries: Record<string, string>): string {
  return (
    Object.keys(entries)
      .sort()
      .map((key) => `${stringsLiteral(key)} = ${stringsLiteral(entries[key]!)};`)
      .join("\n") + "\n"
  );
}

export function buildOutputs(base: string = OUT): Record<string, string> {
  const catalog = build();
  const outputs: Record<string, string> = {
    [join(base, "Catalog", "Localizable.xcstrings")]: JSON.stringify(catalog, null, 2) + "\n",
  };
  for (const locale of ["en", "de"] as const) {
    outputs[join(base, locale + ".lproj", "Localizable.strings")] = renderStrings(
      Object.fromEntries(
        Object.entries(catalog.strings).map(([key, entry]) => [
          key,
          entry.localizations[locale].stringUnit.value,
        ]),
      ),
    );
  }
  return outputs;
}

export function staleOutputs(outputs: Record<string, string>): string[] {
  return Object.entries(outputs)
    .filter(([path, expected]) => {
      try {
        return readFileSync(path, "utf8") !== expected;
      } catch {
        return true;
      }
    })
    .map(([path]) => path);
}

// Build every expected output before writing any of them.
if (import.meta.main) {
  const outputs = buildOutputs();
  if (process.argv.includes("--check")) {
    const stale = staleOutputs(outputs);
    if (stale.length) {
      console.error(
        `Missing/stale localization outputs:\n${stale.join("\n")}\nRun native/scripts/gen-strings.sh.`,
      );
      process.exit(1);
    }
    console.log(`All three localization outputs are up to date (${KEYS.length} keys).`);
  } else {
    for (const [path, text] of Object.entries(outputs)) {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, text, "utf8");
    }
    console.log(`Wrote three localization outputs (${KEYS.length} keys, en + de).`);
  }
}
