// AUTO-GENERATED by ui/scripts/gen-docs-manifest.ts — do not edit by hand.
// Run `bun run gen:docs` (from ui/) to regenerate; `check:docs-manifest` guards drift.
// Source: committed docs-site pages (git ls-files) + sync-docs.mjs PAGES. See #1338.

export type DocsPage = { title: string; path: string; keywords: string };

export const DOCS_PAGES: readonly DocsPage[] = [
  {
    title: "Authoring an epic",
    path: "/authoring-epics/",
    keywords:
      'step-by-step guide to structuring a github epic that shepherd recognizes and can drain — native sub-issues, the epic-dag fence, and the checklist fallback. what "recognized" means create epic from research (guided flow) step 1 — new epic, or promote an existing issue? step 2 — split the work into child issues step 3 — create the children first and capture their numbers step 4 — mark the parent (choose one shape) native sub-issues (preferred) epic-dag fence (markdown) checklist (markdown, no dependencies) step 5 — add dependency edges step 6 — import a markdown epic into native links step 7 — verify in shepherd before draining',
  },
  {
    title: "Shepherd Capture (browser extension)",
    path: "/capture-extension/",
    keywords:
      "install the shepherd capture browser extension and turn any page into a task or session. install from the chrome web store point it at your core what a capture includes open the popup for developers",
  },
  {
    title: "Getting started",
    path: "/getting-started/",
    keywords:
      "install shepherd and sign in. install curl|bash trust note supported platforms installer environment knobs finish setup from-clone / development path requirements next steps",
  },
  {
    title: "Hands-off epics",
    path: "/hands-off-epics/",
    keywords:
      'the automation-pane settings that let an epic drain end-to-end without operator intervention, and the blockers that will still legitimately stop it. recommended settings plan gate is hands-off-safe — keep it on sign-off authority — leave it on "human" what still stops a hands-off epic starting the epic',
  },
  {
    title: "Operating Shepherd",
    path: "/operating/",
    keywords:
      "run shepherd as a systemd service, expose it over tailscale, and deploy code changes. run as a systemd user service expose it over the network deploy a code change backups & restore host tuning — tmpfs inodes",
  },
  {
    title: "CLI reference",
    path: "/reference/cli/",
    keywords: "operator-facing herdr cli commands, generated from live --help.",
  },
  {
    title: "herdr channel",
    path: "/reference/cli/channel/",
    keywords: "choose the stable or preview herdr update channel.",
  },
  {
    title: "herdr server",
    path: "/reference/cli/server/",
    keywords: "control the herdr server lifecycle (stop, reload config).",
  },
  {
    title: "herdr session",
    path: "/reference/cli/session/",
    keywords: "manage named persistent herdr sessions.",
  },
  {
    title: "herdr status",
    path: "/reference/cli/status/",
    keywords: "inspect the local client and the running herdr server.",
  },
  {
    title: "herdr update",
    path: "/reference/cli/update/",
    keywords: "download and install the latest herdr version.",
  },
  {
    title: "Configuration",
    path: "/reference/configuration/",
    keywords:
      "every environment variable and the per-agent sandbox profiles. core live preview host tuning (tmpfs inodes) runaway-orphan reaper main agent terminal renderer (research preview) up next quick-start documentation automation (pr-gated doc agent) anonymous usage telemetry per-agent sandbox / permission profiles",
  },
  {
    title: "External Task API",
    path: "/reference/external-task-api/",
    keywords:
      "submit tasks to shepherd from external agents over plain http. tl;dr why no new endpoint is needed cors / csrf does not block programmatic clients what actually gates access recommended setup for a remote agent request schema responses usage-aware hold gate steering and ending a task",
  },
  {
    title: "Concepts & glossary",
    path: "/reference/glossary/",
    keywords:
      "the shepherd-specific and industry terms used throughout the app and these docs. shepherd concepts epic critic merge train rework inferred lightweight repo trial weighted units reasoning effort satellite pass industry terms pr ci telemetry",
  },
  {
    title: "Project house rules",
    path: "/reference/house-rules/",
    keywords:
      "shepherd's in-repo contributor & agent house rules (claude.md), rendered verbatim. running checks in a fresh worktree branch hygiene (one feature, linear off main) never git stash in a worktree (shared refs/stash) design system (required for any ui work) internationalization (required for any ui work) feature discovery (required for user-facing features) glossary (required when marking ui terms)",
  },
  {
    title: "Keyboard shortcuts",
    path: "/reference/keyboard-shortcuts/",
    keywords:
      "drive the shepherd dashboard from the keyboard — the command bar, session switching, and terminal keys. command bar session & herd navigation switch sessions while the terminal is focused terminal new task",
  },
  {
    title: "Plugins",
    path: "/reference/plugins/",
    keywords:
      "write server-side plugins: spawn hooks, routes, status/ui panels, and gear-menu items. location & loading installing from the ui updates — in place, one click manifest (plugin.json) entry contract the ctx capability seam the onspawn hook failure behavior the single-loop discipline (important) status panel declarative ui panel (publishui) gear-menu item (publishgearitem) three action kinds validation & security additive guard http routes a fuller example: spawn-labeler",
  },
  {
    title: "Security",
    path: "/reference/security/",
    keywords:
      "sandbox membrane, egress firewall, and accepted security residuals. r3 — in-membrane token readability (accepted) attended-mode egress coverage r4 — prompt-injection posture see also",
  },
];
