import Foundation
enum SettingsDiagnosticCopy {
    static func text(_ key: String, params: [String:String]) -> String {
        switch key {
        case "diagnostics_all_ok": return L.t("diagnostics_all_ok")
        case "diagnostics_doc_link": return L.t("diagnostics_doc_link")
        case "diagnostics_fix": return L.t("diagnostics_fix")
        case "diagnostics_fix_action_claude_trust": return L.t("diagnostics_fix_action_claude_trust")
        case "diagnostics_fix_action_host_capacity": return L.t("diagnostics_fix_action_host_capacity", params["memoryHigh"] ?? "—", params["cpuQuota"] ?? "—", params["units"] ?? "—")
        case "diagnostics_fix_action_tmp_inodes": return L.t("diagnostics_fix_action_tmp_inodes")
        case "diagnostics_fix_confirm_body": return L.t("diagnostics_fix_confirm_body")
        case "diagnostics_fix_confirm_run": return L.t("diagnostics_fix_confirm_run")
        case "diagnostics_fix_confirm_run_code": return L.t("diagnostics_fix_confirm_run_code")
        case "diagnostics_fix_confirm_run_host_capacity": return L.t("diagnostics_fix_confirm_run_host_capacity")
        case "diagnostics_fix_confirm_run_tmp_inodes": return L.t("diagnostics_fix_confirm_run_tmp_inodes")
        case "diagnostics_fix_confirm_title": return L.t("diagnostics_fix_confirm_title")
        case "diagnostics_fix_confirm_title_code": return L.t("diagnostics_fix_confirm_title_code")
        case "diagnostics_fix_confirm_title_host_capacity": return L.t("diagnostics_fix_confirm_title_host_capacity")
        case "diagnostics_fix_confirm_title_tmp_inodes": return L.t("diagnostics_fix_confirm_title_tmp_inodes")
        case "diagnostics_fix_failed": return L.t("diagnostics_fix_failed")
        case "diagnostics_fix_running": return L.t("diagnostics_fix_running")
        case "diagnostics_fix_success": return L.t("diagnostics_fix_success")
        case "diagnostics_fix_unresolved": return L.t("diagnostics_fix_unresolved")
        case "diagnostics_fix_unresolved_code": return L.t("diagnostics_fix_unresolved_code")
        case "diagnostics_fix_unresolved_host_capacity": return L.t("diagnostics_fix_unresolved_host_capacity")
        case "diagnostics_fix_unresolved_tmp_inodes": return L.t("diagnostics_fix_unresolved_tmp_inodes")
        case "diagnostics_herdr_downgrade": return L.t("diagnostics_herdr_downgrade")
        case "diagnostics_herdr_repair": return L.t("diagnostics_herdr_repair")
        case "diagnostics_hint_bun_missing": return L.t("diagnostics_hint_bun_missing")
        case "diagnostics_hint_bun_ok": return L.t("diagnostics_hint_bun_ok")
        case "diagnostics_hint_bun_outdated": return L.t("diagnostics_hint_bun_outdated")
        case "diagnostics_hint_claude_install_diverged": return L.t("diagnostics_hint_claude_install_diverged", params["running"] ?? "—", params["managed"] ?? "—")
        case "diagnostics_hint_claude_install_native_on_path": return L.t("diagnostics_hint_claude_install_native_on_path", params["running"] ?? "—")
        case "diagnostics_hint_claude_install_native_residue": return L.t("diagnostics_hint_claude_install_native_residue", params["count"] ?? "—", params["size"] ?? "—")
        case "diagnostics_hint_claude_install_ok": return L.t("diagnostics_hint_claude_install_ok")
        case "diagnostics_hint_claude_missing": return L.t("diagnostics_hint_claude_missing")
        case "diagnostics_hint_claude_ok": return L.t("diagnostics_hint_claude_ok")
        case "diagnostics_hint_claude_optional": return L.t("diagnostics_hint_claude_optional")
        case "diagnostics_hint_claude_trust_ok": return L.t("diagnostics_hint_claude_trust_ok")
        case "diagnostics_hint_claude_trust_untrusted": return L.t("diagnostics_hint_claude_trust_untrusted")
        case "diagnostics_hint_codex_missing": return L.t("diagnostics_hint_codex_missing")
        case "diagnostics_hint_codex_model_chatgpt_incompatible": return L.t("diagnostics_hint_codex_model_chatgpt_incompatible")
        case "diagnostics_hint_codex_ok": return L.t("diagnostics_hint_codex_ok")
        case "diagnostics_hint_codex_optional": return L.t("diagnostics_hint_codex_optional")
        case "diagnostics_hint_gh_missing": return L.t("diagnostics_hint_gh_missing")
        case "diagnostics_hint_gh_not_authenticated": return L.t("diagnostics_hint_gh_not_authenticated")
        case "diagnostics_hint_gh_not_required": return L.t("diagnostics_hint_gh_not_required")
        case "diagnostics_hint_gh_ok": return L.t("diagnostics_hint_gh_ok")
        case "diagnostics_hint_gh_unverified": return L.t("diagnostics_hint_gh_unverified")
        case "diagnostics_hint_git_missing": return L.t("diagnostics_hint_git_missing")
        case "diagnostics_hint_git_ok": return L.t("diagnostics_hint_git_ok")
        case "diagnostics_hint_gitcap_ok": return L.t("diagnostics_hint_gitcap_ok")
        case "diagnostics_hint_gitcap_old": return L.t("diagnostics_hint_gitcap_old")
        case "diagnostics_hint_herdr_health_leftover": return L.t("diagnostics_hint_herdr_health_leftover")
        case "diagnostics_hint_herdr_health_ok": return L.t("diagnostics_hint_herdr_health_ok")
        case "diagnostics_hint_herdr_health_uninspectable": return L.t("diagnostics_hint_herdr_health_uninspectable")
        case "diagnostics_hint_herdr_missing": return L.t("diagnostics_hint_herdr_missing")
        case "diagnostics_hint_herdr_offline": return L.t("diagnostics_hint_herdr_offline")
        case "diagnostics_hint_herdr_ok": return L.t("diagnostics_hint_herdr_ok")
        case "diagnostics_hint_herdr_outdated": return L.t("diagnostics_hint_herdr_outdated")
        case "diagnostics_hint_herdr_restart": return L.t("diagnostics_hint_herdr_restart")
        case "diagnostics_hint_herdr_unknown": return L.t("diagnostics_hint_herdr_unknown")
        case "diagnostics_hint_herdr_unsupported": return L.t("diagnostics_hint_herdr_unsupported")
        case "diagnostics_hint_host_capacity_herdr_unbounded": return L.t("diagnostics_hint_host_capacity_herdr_unbounded")
        case "diagnostics_hint_host_capacity_ok": return L.t("diagnostics_hint_host_capacity_ok")
        case "diagnostics_hint_host_capacity_pressure": return L.t("diagnostics_hint_host_capacity_pressure")
        case "diagnostics_hint_host_capacity_unbounded": return L.t("diagnostics_hint_host_capacity_unbounded")
        case "diagnostics_hint_host_capacity_uninspectable": return L.t("diagnostics_hint_host_capacity_uninspectable")
        case "diagnostics_hint_node_missing": return L.t("diagnostics_hint_node_missing")
        case "diagnostics_hint_node_ok": return L.t("diagnostics_hint_node_ok")
        case "diagnostics_hint_node_outdated": return L.t("diagnostics_hint_node_outdated")
        case "diagnostics_hint_preview_probes_idle": return L.t("diagnostics_hint_preview_probes_idle")
        case "diagnostics_hint_preview_probes_ok": return L.t("diagnostics_hint_preview_probes_ok")
        case "diagnostics_hint_preview_probes_stale": return L.t("diagnostics_hint_preview_probes_stale")
        case "diagnostics_hint_preview_probes_unavailable": return L.t("diagnostics_hint_preview_probes_unavailable")
        case "diagnostics_hint_preview_probes_uninspectable": return L.t("diagnostics_hint_preview_probes_uninspectable")
        case "diagnostics_hint_preview_probes_unsupported": return L.t("diagnostics_hint_preview_probes_unsupported")
        case "diagnostics_hint_pwa_android": return L.t("diagnostics_hint_pwa_android")
        case "diagnostics_hint_pwa_ios": return L.t("diagnostics_hint_pwa_ios")
        case "diagnostics_hint_pwa_optional": return L.t("diagnostics_hint_pwa_optional")
        case "diagnostics_hint_sandbox_membrane_broken": return L.t("diagnostics_hint_sandbox_membrane_broken", params["agent"] ?? "—")
        case "diagnostics_hint_sandbox_membrane_ok": return L.t("diagnostics_hint_sandbox_membrane_ok")
        case "diagnostics_hint_sandbox_membrane_uninspectable": return L.t("diagnostics_hint_sandbox_membrane_uninspectable")
        case "diagnostics_hint_tailscale_missing": return L.t("diagnostics_hint_tailscale_missing")
        case "diagnostics_hint_tailscale_not_serving": return L.t("diagnostics_hint_tailscale_not_serving")
        case "diagnostics_hint_tailscale_ok": return L.t("diagnostics_hint_tailscale_ok")
        case "diagnostics_hint_tailscale_serve_denied": return L.t("diagnostics_hint_tailscale_serve_denied")
        case "diagnostics_hint_tmp_entries_critical": return L.t("diagnostics_hint_tmp_entries_critical")
        case "diagnostics_hint_tmp_entries_high": return L.t("diagnostics_hint_tmp_entries_high")
        case "diagnostics_hint_tmp_entries_ok": return L.t("diagnostics_hint_tmp_entries_ok")
        case "diagnostics_hint_tmp_inodes_critical": return L.t("diagnostics_hint_tmp_inodes_critical")
        case "diagnostics_hint_tmp_inodes_high": return L.t("diagnostics_hint_tmp_inodes_high")
        case "diagnostics_hint_tmp_inodes_ok": return L.t("diagnostics_hint_tmp_inodes_ok")
        case "diagnostics_hint_tmp_inodes_uninspectable": return L.t("diagnostics_hint_tmp_inodes_uninspectable")
        case "diagnostics_label_bun": return L.t("diagnostics_label_bun")
        case "diagnostics_label_claude": return L.t("diagnostics_label_claude")
        case "diagnostics_label_claude_install": return L.t("diagnostics_label_claude_install")
        case "diagnostics_label_claude_trust": return L.t("diagnostics_label_claude_trust")
        case "diagnostics_label_codex": return L.t("diagnostics_label_codex")
        case "diagnostics_label_gh": return L.t("diagnostics_label_gh")
        case "diagnostics_label_git": return L.t("diagnostics_label_git")
        case "diagnostics_label_git_mergetree": return L.t("diagnostics_label_git_mergetree")
        case "diagnostics_label_herdr": return L.t("diagnostics_label_herdr")
        case "diagnostics_label_herdr_health": return L.t("diagnostics_label_herdr_health")
        case "diagnostics_label_host_capacity": return L.t("diagnostics_label_host_capacity")
        case "diagnostics_label_node": return L.t("diagnostics_label_node")
        case "diagnostics_label_preview_probes": return L.t("diagnostics_label_preview_probes")
        case "diagnostics_label_pwa_install": return L.t("diagnostics_label_pwa_install")
        case "diagnostics_label_sandbox_membrane": return L.t("diagnostics_label_sandbox_membrane")
        case "diagnostics_label_tailscale": return L.t("diagnostics_label_tailscale")
        case "diagnostics_label_tmp_inodes": return L.t("diagnostics_label_tmp_inodes")
        case "diagnostics_learn_more": return L.t("diagnostics_learn_more")
        case "diagnostics_load_error": return L.t("diagnostics_load_error")
        case "diagnostics_pip_label": return L.t("diagnostics_pip_label")
        case "diagnostics_rerun": return L.t("diagnostics_rerun")
        case "diagnostics_rerun_error": return L.t("diagnostics_rerun_error")
        case "diagnostics_state_error": return L.t("diagnostics_state_error")
        case "diagnostics_state_installed": return L.t("diagnostics_state_installed")
        case "diagnostics_state_not_installed": return L.t("diagnostics_state_not_installed")
        case "diagnostics_state_ok": return L.t("diagnostics_state_ok")
        case "diagnostics_state_optional": return L.t("diagnostics_state_optional")
        case "diagnostics_state_warning": return L.t("diagnostics_state_warning")
        case "diagnostics_subtitle": return L.t("diagnostics_subtitle")
        case "diagnostics_title": return L.t("diagnostics_title")
        default: return L.t("native_settings_diagnostic_unknown")
        }
    }
}
