#!/usr/bin/env bun
/**
 * Derives `contracts/openapi.swift.yaml` from `contracts/openapi.yaml`.
 *
 * `contracts/openapi.yaml` is the truth the ajv drift test validates against the live server, so
 * it uses the JSON-Schema constructs that describe the wire exactly. Apple's
 * swift-openapi-generator does not support several of them, so Swift is generated from this
 * mechanical derivation instead — never from the truth file:
 *
 *   a. `oneOf`/`anyOf` of one schema plus `{type: "null"}` (apple/swift-openapi-generator#817)
 *      collapses to the non-null schema, and the property drops out of the enclosing `required`
 *      list — a Swift optional decodes JSON null as nil through `decodeIfPresent`.
 *   b. `null` inside an `enum` array (#118) is dropped. The `type: [x, "null"]` array stays; the
 *      generator handles that.
 *   c. `const` (#261) is deleted. The runtime contract test already asserts those literal values.
 *   d. Enum schemas flagged `x-shepherd-open-enum: true` become the generator's documented
 *      open-enum shape (`anyOf: [{enum}, {type: string}]`), because generated Swift enums are
 *      closed and the server can emit a value a shipped client has never heard of.
 *
 * Everything else — `x-shepherd-events`, `x-shepherd-pty`, `additionalProperties`, response-level
 * `$ref`, path-level `parameters` — passes through untouched.
 *
 * Determinism: insertion order is preserved everywhere and the output is formatted with the repo's
 * own prettier, so running this twice yields a byte-identical file. That is what
 * `bun run check:contract-swift` and `test/contract/swift-derivation.test.ts` rely on.
 *
 * Usage: bun run gen:contract-swift
 */
import { readFileSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import prettier from "prettier";
import YAML from "yaml";

const ROOT = join(import.meta.dir, "..");
export const TRUTH_PATH = join(ROOT, "contracts", "openapi.yaml");
export const DERIVED_PATH = join(ROOT, "contracts", "openapi.swift.yaml");

export const GENERATED_HEADER =
  "# GENERATED by scripts/gen-contract-swift.ts from contracts/openapi.yaml — do not edit";

/** The flag F2 puts on read-side enums the server may outgrow. */
const OPEN_ENUM = "x-shepherd-open-enum";

type Obj = Record<string, unknown>;

function isObj(v: unknown): v is Obj {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

/** Exactly `{type: "null"}` — the null branch of a nullable union. */
function isNullBranch(v: unknown): boolean {
  return isObj(v) && Object.keys(v).length === 1 && v.type === "null";
}

/** For `{oneOf|anyOf: [X, {type: "null"}]}` returns the union keyword and X; null otherwise. */
function nullableUnion(node: Obj): { keyword: string; inner: Obj } | null {
  for (const keyword of ["oneOf", "anyOf"]) {
    const branches = node[keyword];
    if (!Array.isArray(branches) || branches.length !== 2) continue;
    const nulls = branches.filter(isNullBranch);
    const rest = branches.filter((b) => !isNullBranch(b));
    if (nulls.length === 1 && rest.length === 1 && isObj(rest[0])) {
      return { keyword, inner: rest[0] };
    }
  }
  return null;
}

/** True when the derivation makes this property schema optional rather than nullable: rule (a),
 *  and rule (d) for a flagged enum that was `type: [string, "null"]`. */
function becomesOptional(schema: unknown): boolean {
  if (!isObj(schema)) return false;
  if (nullableUnion(schema)) return true;
  if (schema[OPEN_ENUM] !== true) return false;
  return Array.isArray(schema.type) ? schema.type.includes("null") : schema.type === "null";
}

/** Rule (d): an open enum becomes `anyOf: [{type: string, enum: [...]}, {type: string}]`, so an
 *  unknown member decodes into the generator's `case other(String)` instead of failing. */
function openEnum(node: Obj): Obj {
  const out: Obj = {};
  for (const [k, v] of Object.entries(node)) {
    if (k === OPEN_ENUM || k === "type" || k === "enum") continue;
    out[k] = v;
  }
  const members = Array.isArray(node.enum) ? node.enum.filter((m) => m !== null) : [];
  out.anyOf = [{ type: "string", enum: members }, { type: "string" }];
  return out;
}

/** Applies every rule to `node` and, recursively, to everything under it. */
function transform(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(transform);
  if (!isObj(node)) return node;

  // Rule (a) first: collapse the nullable union, then keep transforming the schema it left behind
  // (the inner schema may itself be an open enum or carry a `const`).
  const union = nullableUnion(node);
  if (union) {
    const merged: Obj = {};
    for (const [k, v] of Object.entries(node)) {
      if (k === union.keyword) {
        for (const [ik, iv] of Object.entries(union.inner)) merged[ik] = iv;
      } else {
        merged[k] = v;
      }
    }
    return transform(merged);
  }

  // Rule (d) before the generic walk, so the branches it builds are walked too.
  if (node[OPEN_ENUM] === true) return transform(openEnum(node));

  const out: Obj = {};
  for (const [key, value] of Object.entries(node)) {
    if (key === "const") continue; // rule (c)
    if (key === "enum" && Array.isArray(value)) {
      out[key] = value.filter((m) => m !== null); // rule (b)
      continue;
    }
    out[key] = transform(value);
  }

  // Rules (a)/(d) turned some nullable properties into optional ones — drop them from `required`.
  if (isObj(node.properties) && Array.isArray(out.required)) {
    const props = node.properties;
    out.required = out.required.filter(
      (name) => typeof name !== "string" || !becomesOptional(props[name]),
    );
  }
  return out;
}

/** The whole derivation: truth YAML text in, generator-input YAML text out. */
export async function deriveSwiftSpec(truthYaml: string): Promise<string> {
  const truth = YAML.parse(truthYaml) as unknown;
  const derived = transform(truth);
  const body = YAML.stringify(derived, { lineWidth: 0 });
  const cfg = await prettier.resolveConfig(DERIVED_PATH);
  return prettier.format(`${GENERATED_HEADER}\n${body}`, { ...cfg, parser: "yaml" });
}

export async function generate(): Promise<string> {
  return deriveSwiftSpec(readFileSync(TRUTH_PATH, "utf8"));
}

if (import.meta.main) {
  const text = await generate();
  await writeFile(DERIVED_PATH, text);
  console.log(`wrote ${DERIVED_PATH}`);
}
