#!/usr/bin/env bun
/**
 * Derives `contracts/openapi.rust.yaml` from `contracts/openapi.yaml`.
 *
 * `contracts/openapi.yaml` is OpenAPI 3.1 and the truth the ajv drift test validates the live server
 * against. The Rust `shepherd` CLI generates its client with oxidecomputer/progenitor, which only
 * reads OpenAPI 3.0, so Rust is generated from this mechanical derivation instead — never from the
 * truth file (mirrors scripts/gen-contract-swift.ts):
 *
 *   a. `openapi: 3.1.x` becomes `3.0.3`.
 *   b. A type array `type: [T, "null"]` becomes `type: T` + `nullable: true`.
 *   c. `oneOf`/`anyOf` of one schema plus `{type: "null"}` becomes the schema + `nullable: true`;
 *      a `$ref` branch is wrapped as `allOf: [$ref]`, because 3.0 ignores keys beside a `$ref`.
 *   d. `const: v` becomes `enum: [v]` (3.0 has no `const`).
 *   e. A `null` member of an `enum` is dropped; the nullability rides on (b).
 *   f. An enum flagged `x-shepherd-open-enum: true` loses its `enum` list and decodes as a plain
 *      string. Generated Rust enums are closed, and the server can emit a member a shipped CLI has
 *      never heard of — which would fail the whole response.
 *   g. `x-shepherd-explicit-null` scalars are already `type: [boolean|string, "null"]`: (b) applies.
 *   h. An operation whose 2xx (or error) statuses answer different bodies gets one shared body
 *      type — see unifyResponses.
 *   i. An operation progenitor cannot generate at all is dropped — see RUST_EXCLUDED_OPERATIONS.
 *
 * The walk is schema-aware like the Swift one: it only rewrites where a JSON Schema lives
 * (`components.schemas` values, `properties`/`items`/`additionalProperties`/`allOf`/`anyOf`/
 * `oneOf`/`not` inside a schema, and any `schema` value). The KEYS of `properties` are names, never
 * keywords. It is strict: a construct it cannot rewrite faithfully throws with its JSON pointer.
 *
 * Determinism: insertion order is preserved and the output is formatted with the repo's prettier,
 * so `bun run check:contract-rust` and test/contract/rust-derivation.test.ts can diff it.
 *
 * Usage: bun run gen:contract-rust
 */
import { readFileSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import prettier from "prettier";
import YAML from "yaml";

const ROOT = join(import.meta.dir, "..");
export const TRUTH_PATH = join(ROOT, "contracts", "openapi.yaml");
export const DERIVED_PATH = join(ROOT, "contracts", "openapi.rust.yaml");

export const GENERATED_HEADER =
  "# GENERATED by scripts/gen-contract-rust.ts from contracts/openapi.yaml — do not edit";

export const RUST_OPENAPI_VERSION = "3.0.3";

const OPEN_ENUM = "x-shepherd-open-enum";
const EXPLICIT_NULL = "x-shepherd-explicit-null";

/** The only keys allowed beside a nullable union: annotations. */
const UNION_ANNOTATIONS = new Set(["description", "title", "deprecated"]);

/** Keywords OpenAPI 3.0 does not have (or has with another meaning) and this derivation has no
 *  rule for. Meeting one is a hard error rather than a verbatim copy progenitor would misread. */
const UNHANDLED_SCHEMA_KEYWORDS = new Set([
  "patternProperties",
  "propertyNames",
  "prefixItems",
  "contains",
  "dependentSchemas",
  "dependentRequired",
  "unevaluatedProperties",
  "unevaluatedItems",
  "if",
  "then",
  "else",
  "examples",
  "$defs",
  "contentMediaType",
  "contentEncoding",
]);

type Obj = Record<string, unknown>;

function isObj(v: unknown): v is Obj {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function isAnnotation(key: string): boolean {
  return UNION_ANNOTATIONS.has(key) || key.startsWith("x-");
}

/** RFC 6901 escaping, so the pointer in an error message is copy-pasteable. */
function ptr(base: string, token: string): string {
  return `${base}/${token.replace(/~/g, "~0").replace(/\//g, "~1")}`;
}

function isNullBranch(v: unknown): boolean {
  return isObj(v) && Object.keys(v).length === 1 && v.type === "null";
}

/** For `{oneOf|anyOf: [X, {type: "null"}]}` returns the union keyword and X; null otherwise. */
function nullableUnion(node: Obj): { keyword: string; inner: Obj } | null {
  for (const keyword of ["oneOf", "anyOf"]) {
    const branches = node[keyword];
    if (!Array.isArray(branches) || branches.length !== 2) continue;
    const nulls = branches.filter(isNullBranch);
    const rest = branches.filter((b) => !isNullBranch(b));
    if (nulls.length === 1 && rest.length === 1 && isObj(rest[0])) {
      return { keyword, inner: rest[0] };
    }
  }
  return null;
}

/** Rule (b): `[T, "null"]` → `{type: T, nullable: true}`; any other array is unrepresentable. */
function typeArray(types: unknown[], pointer: string): { type: unknown; nullable: boolean } {
  const rest = types.filter((t) => t !== "null");
  if (rest.length !== 1 || typeof rest[0] !== "string") {
    throw new Error(
      `unsupported type array at ${pointer}: OpenAPI 3.0 allows one type plus nullable, got ${JSON.stringify(types)}`,
    );
  }
  return { type: rest[0], nullable: rest.length !== types.length };
}

/** Rule (c): collapse a nullable union into the non-null schema plus `nullable: true`. */
function collapseUnion(node: Obj, union: { keyword: string; inner: Obj }, pointer: string): Obj {
  const offenders = Object.keys(node).filter((k) => k !== union.keyword && !isAnnotation(k));
  if (offenders.length > 0) {
    throw new Error(
      `unsupported nullable union at ${pointer}: the union carries sibling keys [${offenders.join(", ")}] that the collapse would drop — move them into the non-null branch`,
    );
  }
  const out: Obj = {};
  for (const [k, v] of Object.entries(node)) {
    if (k === union.keyword) {
      // A 3.0 `$ref` swallows its siblings, so `nullable` needs an `allOf` wrapper to survive.
      if (typeof union.inner.$ref === "string") out.allOf = [union.inner];
      else Object.assign(out, union.inner);
    } else {
      out[k] = v;
    }
  }
  out.nullable = true;
  return out;
}

function transformSchema(node: Obj, pointer: string): Obj {
  for (const key of Object.keys(node)) {
    if (UNHANDLED_SCHEMA_KEYWORDS.has(key)) {
      throw new Error(
        `unsupported schema keyword "${key}" at ${pointer}: the derivation has no rule for it — model it with the keywords the contract already uses`,
      );
    }
  }
  if (
    (typeof node.exclusiveMinimum === "number" || typeof node.exclusiveMaximum === "number") &&
    !("minimum" in node || "maximum" in node)
  ) {
    throw new Error(
      `unsupported numeric exclusive bound at ${pointer}: OpenAPI 3.0 spells it as a boolean beside minimum/maximum — use minimum/maximum`,
    );
  }

  const union = nullableUnion(node);
  if (union) return transformSchema(collapseUnion(node, union, pointer), pointer);

  const openEnum = node[OPEN_ENUM] === true;
  const out: Obj = {};
  for (const [key, value] of Object.entries(node)) {
    const here = ptr(pointer, key);
    if (key === OPEN_ENUM || key === EXPLICIT_NULL) continue;
    if (key === "type" && Array.isArray(value)) {
      const { type, nullable } = typeArray(value, here);
      out.type = type;
      if (nullable) out.nullable = true;
      continue;
    }
    if (key === "const") {
      out.enum = [value]; // rule (d)
      continue;
    }
    if (key === "enum" && Array.isArray(value)) {
      if (!openEnum) out.enum = value.filter((m) => m !== null); // rules (e) / (f)
      continue;
    }
    if (key === "properties" && isObj(value)) {
      const props: Obj = {};
      for (const [name, sub] of Object.entries(value)) {
        props[name] = isObj(sub) ? transformSchema(sub, ptr(here, name)) : sub;
      }
      out[key] = props;
      continue;
    }
    if ((key === "items" || key === "not" || key === "additionalProperties") && isObj(value)) {
      out[key] = transformSchema(value, here);
      continue;
    }
    if ((key === "allOf" || key === "anyOf" || key === "oneOf") && Array.isArray(value)) {
      out[key] = value.map((branch, i) =>
        isObj(branch) ? transformSchema(branch, `${here}/${i}`) : branch,
      );
      continue;
    }
    out[key] = value;
  }
  return out;
}

/**
 * Rule (i): operations with no faithful 3.0 rewrite progenitor accepts, operationId → why. The
 * path item is removed with its last operation. The CLI must never depend on one of these; the
 * derivation test asserts the v1 CLI surface is untouched.
 */
export const RUST_EXCLUDED_OPERATIONS: Record<string, string> = {
  uploadFile: "multipart/form-data request body — progenitor 0.15 rejects the content type",
};

function excludeOperations(doc: Obj): void {
  if (!isObj(doc.paths)) return;
  for (const [path, item] of Object.entries(doc.paths)) {
    if (!isObj(item)) continue;
    for (const [method, op] of Object.entries(item)) {
      if (
        isObj(op) &&
        typeof op.operationId === "string" &&
        op.operationId in RUST_EXCLUDED_OPERATIONS
      )
        delete item[method];
    }
    if (!Object.values(item).some((op) => isObj(op) && "operationId" in op)) delete doc.paths[path];
  }
}

/**
 * Rule (h): progenitor gives an operation ONE success type and ONE error type (it asserts
 * `response_types.len() <= 1` in progenitor-impl's method.rs). Where the truth answers different
 * bodies across the 2xx statuses — or across the error statuses — of one operation:
 *
 *   - differing JSON schemas → a named component `<OperationId>Success` / `<OperationId>Error`
 *     holding `oneOf` of them, referenced by every response in the group. typify renders it as an
 *     untagged enum; the generic `Error` schema is ordered last so a richer body is tried first.
 *     The status codes are unchanged, so a caller still branches on `status()`.
 *   - an error group mixing bodyless and JSON responses → every error in the group loses its body
 *     schema (progenitor then hands back the raw body). Errors only: a success group like that
 *     throws, because dropping a success body would silently lose data.
 */
const GENERIC_ERROR_REF = "#/components/schemas/Error";

type ResponseGroup = { suffix: "Success" | "Error"; statuses: string[] };

function resolveResponse(doc: Obj, resp: unknown, pointer: string): Obj {
  if (!isObj(resp)) throw new Error(`unsupported response at ${pointer}`);
  if (typeof resp.$ref !== "string") return resp;
  const name = resp.$ref.replace("#/components/responses/", "");
  const target =
    isObj(doc.components) && isObj(doc.components.responses)
      ? doc.components.responses[name]
      : undefined;
  if (!isObj(target)) throw new Error(`unresolvable response $ref at ${pointer}: ${resp.$ref}`);
  return structuredClone(target);
}

/** The body a response declares: null when bodyless, else its `application/json` schema. */
function responseBody(resp: Obj, pointer: string): unknown {
  if (!isObj(resp.content)) return null;
  const types = Object.keys(resp.content);
  const json = resp.content["application/json"];
  if (types.length !== 1 || !isObj(json) || !("schema" in json)) {
    throw new Error(
      `unsupported response content at ${pointer}: expected one application/json schema, got [${types.join(", ")}]`,
    );
  }
  return json.schema;
}

function responseGroups(responses: Obj): ResponseGroup[] {
  const statuses = Object.keys(responses);
  return [
    { suffix: "Success", statuses: statuses.filter((s) => s.startsWith("2")) },
    { suffix: "Error", statuses: statuses.filter((s) => !s.startsWith("2")) },
  ];
}

/** Distinct bodies in a group, first-appearance order; null stands for "bodyless". */
function distinctBodies(bodies: unknown[]): unknown[] {
  const seen = new Map<string, unknown>();
  for (const b of bodies) seen.set(JSON.stringify(b), b);
  return [...seen.values()];
}

function unifyGroup(doc: Obj, op: Obj, group: ResponseGroup, pointer: string): void {
  const responses = op.responses as Obj;
  const resolved = group.statuses.map((s) => resolveResponse(doc, responses[s], ptr(pointer, s)));
  const bodies = resolved.map((r, i) => responseBody(r, ptr(pointer, group.statuses[i]!)));
  const distinct = distinctBodies(bodies);
  if (distinct.length <= 1) return;
  if (distinct.includes(null)) {
    if (group.suffix === "Success") {
      throw new Error(
        `unsupported success responses at ${pointer}: bodyless and JSON 2xx cannot share one progenitor type`,
      );
    }
    group.statuses.forEach((s, i) => {
      const rest = { ...resolved[i]! };
      delete rest.content;
      responses[s] = rest;
    });
    return;
  }
  const opId = op.operationId as string;
  const name = `${opId[0]!.toUpperCase()}${opId.slice(1)}${group.suffix}`;
  const schemas = (doc.components as Obj).schemas as Obj;
  if (name in schemas)
    throw new Error(`cannot unify responses at ${pointer}: component "${name}" already exists`);
  const generic = (b: unknown) => isObj(b) && b.$ref === GENERIC_ERROR_REF;
  schemas[name] = {
    description: `Rust-only: every ${group.suffix.toLowerCase()} body ${opId} can answer (statuses ${group.statuses.join(", ")}).`,
    oneOf: [...distinct.filter((b) => !generic(b)), ...distinct.filter(generic)],
  };
  group.statuses.forEach((s, i) => {
    const resp = resolved[i]!;
    responses[s] = {
      ...resp,
      content: { "application/json": { schema: { $ref: `#/components/schemas/${name}` } } },
    };
  });
}

function unifyResponses(doc: Obj): void {
  if (!isObj(doc.paths)) return;
  for (const [path, item] of Object.entries(doc.paths)) {
    if (!isObj(item)) continue;
    for (const [method, op] of Object.entries(item)) {
      if (!isObj(op) || typeof op.operationId !== "string" || !isObj(op.responses)) continue;
      const pointer = ptr(ptr(ptr("#/paths", path), method), "responses");
      for (const group of responseGroups(op.responses)) unifyGroup(doc, op, group, pointer);
    }
  }
}

/** operationIds that still give progenitor more than one success or error body. Empty for the
 *  derived document — the derivation test asserts it. */
export function responseTypeConflicts(doc: Obj): string[] {
  const out: string[] = [];
  for (const [path, item] of Object.entries(isObj(doc.paths) ? doc.paths : {})) {
    if (!isObj(item)) continue;
    for (const [method, op] of Object.entries(item)) {
      if (!isObj(op) || !isObj(op.responses)) continue;
      const pointer = `${path} ${method}`;
      for (const group of responseGroups(op.responses)) {
        const bodies = group.statuses.map((s) =>
          responseBody(resolveResponse(doc, (op.responses as Obj)[s], pointer), pointer),
        );
        if (distinctBodies(bodies).length > 1)
          out.push(`${String(op.operationId)} ${group.suffix}`);
      }
    }
  }
  return out;
}

function walkDocument(node: unknown, pointer: string, inComponents: boolean): unknown {
  if (Array.isArray(node)) return node.map((v, i) => walkDocument(v, `${pointer}/${i}`, false));
  if (!isObj(node)) return node;
  const out: Obj = {};
  for (const [key, value] of Object.entries(node)) {
    const here = ptr(pointer, key);
    if (inComponents && key === "schemas" && isObj(value)) {
      const map: Obj = {};
      for (const [name, schema] of Object.entries(value)) {
        map[name] = isObj(schema) ? transformSchema(schema, ptr(here, name)) : schema;
      }
      out[key] = map;
      continue;
    }
    if (key === "schema" && isObj(value)) {
      out[key] = transformSchema(value, here);
      continue;
    }
    out[key] = walkDocument(value, here, pointer === "#" && key === "components");
  }
  return out;
}

/** The whole derivation: truth YAML text in, progenitor-input YAML text out. */
export async function deriveRustSpec(truthYaml: string): Promise<string> {
  const truth = YAML.parse(truthYaml) as Obj;
  excludeOperations(truth);
  unifyResponses(truth);
  const derived = walkDocument(truth, "#", false) as Obj;
  derived.openapi = RUST_OPENAPI_VERSION;
  const body = YAML.stringify(derived, { lineWidth: 0 });
  const cfg = await prettier.resolveConfig(DERIVED_PATH);
  return prettier.format(`${GENERATED_HEADER}\n${body}`, { ...cfg, parser: "yaml" });
}

export async function generate(): Promise<string> {
  return deriveRustSpec(readFileSync(TRUTH_PATH, "utf8"));
}

if (import.meta.main) {
  const text = await generate();
  await writeFile(DERIVED_PATH, text);
  console.log(`wrote ${DERIVED_PATH}`);
}
