// Map the accented letters German (and a few neighbours) prompts carry onto their
// ASCII transliteration BEFORE we strip non-alphanumerics — otherwise "würde"
// becomes the unreadable "w-rde" instead of "wuerde".
const TRANSLIT: Record<string, string> = {
  ä: "ae",
  ö: "oe",
  ü: "ue",
  ß: "ss",
  à: "a",
  á: "a",
  â: "a",
  é: "e",
  è: "e",
  ê: "e",
  í: "i",
  ì: "i",
  ó: "o",
  ò: "o",
  ô: "o",
  ú: "u",
  ù: "u",
  ñ: "n",
  ç: "c",
};

// Filler words (DE + EN) plus common German exclamations that carry no topical
// meaning. Dropping them keeps the subject of the prompt, not the scaffolding:
// "Mist. Scrollen mit dem Mausrad…" → "scrollen-mausrad", not "mist-scrollen-mit-dem".
const STOPWORDS = new Set([
  // German articles / pronouns / prepositions / particles
  "der",
  "die",
  "das",
  "den",
  "dem",
  "des",
  "ein",
  "eine",
  "einen",
  "einem",
  "einer",
  "eines",
  "und",
  "oder",
  "aber",
  "mit",
  "fuer",
  "von",
  "vom",
  "zu",
  "zum",
  "zur",
  "im",
  "in",
  "an",
  "auf",
  "aus",
  "bei",
  "nach",
  "ueber",
  "unter",
  "vor",
  "durch",
  "gegen",
  "ohne",
  "um",
  "als",
  "wie",
  "so",
  "dass",
  "wenn",
  "weil",
  "ich",
  "du",
  "er",
  "sie",
  "es",
  "wir",
  "ihr",
  "mich",
  "dich",
  "sich",
  "uns",
  "euch",
  "mir",
  "dir",
  "ihm",
  "ihn",
  "ist",
  "sind",
  "war",
  "waren",
  "bin",
  "bist",
  "sein",
  "seine",
  "haben",
  "hat",
  "hatte",
  "habe",
  "werde",
  "wird",
  "wurde",
  "worden",
  "noch",
  "schon",
  "mal",
  "bitte",
  "gerne",
  "gern",
  "doch",
  "etwas",
  "nur",
  "auch",
  "nicht",
  "kein",
  "keine",
  "dann",
  "hier",
  "da",
  "dort",
  "jetzt",
  "man",
  "moechte",
  "wuerde",
  "koennte",
  "sollte",
  "muss",
  "kann",
  "soll",
  "will",
  "diese",
  "dieser",
  "dieses",
  "mein",
  "meine",
  "dein",
  "deine",
  "alle",
  "alles",
  // German exclamations / filler interjections
  "mist",
  "verdammt",
  "hey",
  "ok",
  "okay",
  "also",
  "halt",
  "eben",
  "einfach",
  "tja",
  "naja",
  "ach",
  // English
  "the",
  "a",
  "an",
  "and",
  "or",
  "but",
  "with",
  "for",
  "of",
  "to",
  "from",
  "on",
  "at",
  "by",
  "into",
  "about",
  "is",
  "are",
  "was",
  "were",
  "be",
  "been",
  "being",
  "this",
  "that",
  "these",
  "those",
  "i",
  "you",
  "he",
  "she",
  "it",
  "we",
  "they",
  "me",
  "my",
  "your",
  "our",
  "do",
  "does",
  "did",
  "have",
  "has",
  "had",
  "will",
  "would",
  "can",
  "could",
  "should",
  "must",
  "just",
  "please",
  "not",
  "no",
  "then",
  "if",
  "as",
  "some",
  "only",
  "there",
  "now",
  "make",
  "add",
  "fix",
]);

function transliterate(s: string): string {
  return s.replace(/[äöüßàáâéèêíìóòôúùñç]/gi, (c) => TRANSLIT[c.toLowerCase()] ?? c);
}

/**
 * Turn arbitrary prompt text into a short, human-readable kebab-case slug.
 * Transliterates accents, strips filler words, and keeps the first 1–2 topical
 * words — so the name reads like a marker ("scrollen-mausrad") rather than the
 * raw opening of a sentence. Falls back to the raw words if filtering wiped
 * everything (a prompt made entirely of stopwords), and to "" if truly empty.
 */
export function normalize(s: string): string {
  const words = transliterate(s)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  const meaningful = words.filter((w) => w.length > 1 && !STOPWORDS.has(w));
  return (meaningful.length ? meaningful : words).slice(0, 2).join("-");
}

/**
 * Derive a session name from a task prompt. Pure and deterministic — no network,
 * no local model. The salient words of a task prompt are already in the prompt,
 * so a heuristic slug matches or beats a local LLM for a 1–2 word name
 * (benchmarked in PR #83) without the RAM/latency cost.
 */
export function generateName(prompt: string): string {
  return normalize(prompt) || "task";
}
